# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
